nome = input('Digite seu nome completo: ').strip()
print('Analizando seu nome...')
print('O seu nome com todas as letras em maiúsculas é : {}'.format(nome.upper()))
print('Seu nome com todas as letras em minúsculas é: {}'.format(nome.lower()))
nomediv = nome.split()
print('Seu nome tem {} caractéres sem considerar os espaços'.format(len(''.join(nomediv))))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu primeiro nome {} tem {} letras.'.format(nomediv[0], len(nomediv[0])))
#Uma melhor forma de sumir com os espaços e: .format(len(nome) - count(' '))