nome = input('Digite seu nome completo: ').title().strip()
divi = nome.split()
print('Muito prazer te conhecer!')
print('O seu primeiro nome do usuario e {}'.format(divi[0]))
print('O seu ultimo nome e {}'.format(divi[len(divi)-1]))